FROM node:20.5.1

RUN npm i -dg @dcloudio/uni-components @dcloudio/types @dcloudio/uni-debugger @dcloudio/uni-automator @dcloudio/uni-cli-i18n @dcloudio/vue-cli-plugin-uni @dcloudio/vue-cli-plugin-hbuilderx @dcloudio/uni-stat @dcloudio/uni-mp-weixin @dcloudio/uni-template-compiler @dcloudio/vue-cli-plugin-uni-optimize