name: Build TDesign MiniProgram

on:
  push:
    branches:
      - main

jobs:
  build-tdesign:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Tencent/tdesign-miniprogram
          ref: 1.0.4

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          npm i
          npm run build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Dist
          path: miniprogram_dist
          retention-days: 90
