name: Build TDesign MiniProgram

on:
  push:
    branches:
      - main

jobs:
  build-tdesign:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Tencent/tdesign-miniprogram
        run: |
          git checkout 1.0.4
          git pull

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
