name: Build TDesign MiniProgram

on:
  push:
    paths:
      - ".github/workflows/BuildTDesignWeapp.yml"

env:
  version: 1.3.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tdesign:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Tencent/tdesign-miniprogram
          ref: ${{ env.version }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          npm i
          npm run build
          tar -czvf TDesign-${{ env.version }}.tar.gz miniprogram_dist/
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          artifacts: TDesign-${{ env.version }}.tar.gz
          tag: TDesign-${{ env.version }}
