name: Build KubeKey

on:
  push:
    paths:
      - ".github/workflows/BuildKubeKey.yml"

env:
  version: 3.1.2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kubekey:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kubesphere/kubekey
          ref: v${{ env.version }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          make kk

          curl -s 'https://api.github.com/repos/kubesphere/kubekey/releases/tags/v${{ env.version }}' | jq --raw-output '.body' > /tmp/release.md
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ./bin/kk
          tag: kubekey-${{ env.version }}-kk
          bodyFile: /tmp/release.md
