name: Refresh Image

on:
  push:
    paths:
      - ".github/workflows/BuildRefresh.yml"

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE

          echo "2"

          for name in `ls -l | grep ^d | awk '{print $NF}'`; do
            if [[ "$name" =~ ^"runnergo_" ]]; then
              continue
            fi

            if [[ "$name" =~ ^"nginx-openresty-" ]]; then
              continue
            fi

            if [[ "$name" =~ ^"nginx-vts" ]]; then
              continue
            fi

            podman build -q --no-cache --format docker -t $GITHUB_REPOSITORY:$name ./$name/
            podman tag $GITHUB_REPOSITORY:$name $REGISTRY/$GITHUB_REPOSITORY:$name
            podman push $REGISTRY/$GITHUB_REPOSITORY:$name
          done
