name: Build Skopeo

on:
  push:
    paths:
      - ".github/workflows/BuildSkopeo.yml"

env:
  version: v1.16.1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-skopeo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: containers/skopeo
          ref: ${{ env.version }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE

          sudo apt-get update
          sudo apt-get install -y libgpgme-dev

          make bin/skopeo
          cd bin/
          ls -lh
