name: Build Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE

          for name in $(git diff --name-only HEAD^ HEAD | awk -F/ '{print $1}' | sort -u); do
            if [[ $name == .* ]]; then
              continue
            fi

            if [ "$name" = "grafana-test" ]; then
              git clone -b v10.0.1 https://github.com/grafana/grafana.git $name
              sed -i "s+//raw.githubusercontent.com+//ghproxy.com/https://raw.githubusercontent.com+" ./$name/pkg/services/updatechecker/grafana.go
              docker build --no-cache -t $GITHUB_REPOSITORY:$name ./$name/
              docker tag $GITHUB_REPOSITORY:$name $REGISTRY/$GITHUB_REPOSITORY:$name
              docker push $REGISTRY/$GITHUB_REPOSITORY:$name
              continue
            fi

            if [[ "$name" =~ ^"runnergo_" ]]; then
              docker buildx create --name builder_$name --driver docker-container
              docker buildx use builder_$name
              docker buildx build --platform=linux/amd64,linux/arm64 -t $REGISTRY/$GITHUB_REPOSITORY:$name --push ./$name/
              continue
            fi

            if [ -e "$name/Dockerfile" ]; then
              docker build --no-cache -t $GITHUB_REPOSITORY:$name ./$name/
              docker tag $GITHUB_REPOSITORY:$name $REGISTRY/$GITHUB_REPOSITORY:$name
              docker push $REGISTRY/$GITHUB_REPOSITORY:$name
            fi
          done
