name: Build Docker image (multi-platform)

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the build'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.name }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    outputs:
      IMAGE_DIGEST: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        id: push
        with:
          context: ./${{ github.event.inputs.name }}
          platforms: linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.inputs.name }}

      - uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
