name: Build TDesign MiniProgram

on:
  push:
    branches:
      - main

jobs:
  build-tdesign:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          git clone github.com/Tencent/tdesign-miniprogram
          cd tdesign-miniprogram
          git checkout 1.0.4
          git pull
