name: Build Skopeo

on:
  push:
    paths:
      - ".github/workflows/BuildSkopeo.yml"

env:
  version: 1.16.1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-skopeo:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: containers/skopeo
          ref: v${{ env.version }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE

          sudo apt-get update
          sudo apt-get install -y libgpgme-dev

          curl -s 'https://api.github.com/repos/containers/skopeo/releases/tags/v${{ env.version }}' | jq '.body' > /tmp/release.md

          make binary DISABLE_CGO=1
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: bin/skopeo
          tag: skopeo-${{ env.version }}
          bodyFile: /tmp/release.md
