name: Build TDesign MiniProgram

on:
  push:
    branches:
      - main

jobs:
  build-tdesign:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: Tencent/tdesign-miniprogram
          ref: d81e812efe41c50640c60cac9b8c1ec699c09b62

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
