name: Build KubeKey

on:
  push:
    paths:
      - ".github/workflows/BuildKubeKey.yml"

env:
  version: v3.0.9

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kubekey:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: kubesphere/kubekey
          ref: ${{ env.version }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          make kk
          chmod +x ./bin/kk
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          artifacts: ./bin/kk
          tag: kubekey-${{ env.version }}-kk
