name: Build Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE

          for name in $(git diff --name-only HEAD^ HEAD | awk -F/ '{print $1}' | sort -u); do
            if [[ $name == .* ]]; then
              continue
            fi

            if [[ "$name" =~ ^"runnergo_" ]]; then
              docker buildx create --name builder_$name --driver docker-container
              docker buildx use builder_$name
              docker buildx build --no-cache --platform=linux/amd64,linux/arm64 -t $REGISTRY/$GITHUB_REPOSITORY:$name --push ./$name/
              continue
            fi

            if [ -e "$name/Dockerfile" ]; then
              podman build --no-cache --format docker -t $GITHUB_REPOSITORY:$name ./$name/
              podman tag $GITHUB_REPOSITORY:$name $REGISTRY/$GITHUB_REPOSITORY:$name
              podman push $REGISTRY/$GITHUB_REPOSITORY:$name
            fi
          done
